export const enterTransitions = [
  { name: "BackIn Down", value: "animate__backInDown" },
  { name: "BackIn Left", value: "animate__backInLeft" },
  { name: "BackIn Right", value: "animate__backInRight" },
  { name: "BackIn Up", value: "animate__backInUp" },
  { name: "BounceIn", value: "animate__bounceIn" },
  { name: "BounceIn Down", value: "animate__bounceInDown" },
  { name: "BounceIn Left", value: "animate__bounceInLeft" },
  { name: "BounceIn Right", value: "animate__bounceInRight" },
  { name: "BounceIn Up", value: "animate__bounceInUp" },
  { name: "FadeIn", value: "animate__fadeIn" },
  { name: "FadeIn Down", value: "animate__fadeInDown" },
  { name: "FadeIn Down Big", value: "animate__fadeInDownBig" },
  { name: "FadeIn Left", value: "animate__fadeInLeft" },
  { name: "FadeIn Left Big", value: "animate__fadeInLeftBig" },
  { name: "FadeIn Right", value: "animate__fadeInRight" },
  { name: "FadeIn Right Big", value: "animate__fadeInRightBig" },
  { name: "FadeIn Up", value: "animate__fadeInUp" },
  { name: "FadeIn Up Big", value: "animate__fadeInUpBig" },
  { name: "FadeIn TopLeft", value: "animate__fadeInTopLeft" },
  { name: "FadeIn TopRight", value: "animate__fadeInTopRight" },
  { name: "FadeIn BottomLeft", value: "animate__fadeInBottomLeft" },
  { name: "FadeIn BottemRight", value: "animate__fadeInBottomRight" },
  { name: "FlipIn X", value: "animate__flipInX" },
  { name: "FlipIn Y", value: "animate__flipInY" },
  { name: "LightSpeedIn Right", value: "animate__lightSpeedInRight" },
  { name: "LightSpeedIn Left", value: "animate__lightSpeedInLeft" },
  { name: "RotateIn", value: "animate__rotateIn" },
  { name: "RotateIn DownLeft", value: "animate__rotateInDownLeft" },
  { name: "RotateIn DownRight", value: "animate__rotateInDownRight" },
  { name: "RotateIn UpLeft", value: "animate__rotateInUpLeft" },
  { name: "RotateIn UpRight", value: "animate__rotateInUpRight" },
  { name: "JackInTheBox", value: "animate__jackInTheBox" },
  { name: "RollIn", value: "animate__rollIn" },
  { name: "ZoomIn", value: "animate__zoomIn" },
  { name: "ZoomIn Down", value: "animate__zoomInDown" },
  { name: "ZoomIn Left", value: "animate__zoomInLeft" },
  { name: "ZoomIn Right", value: "animate__zoomInRight" },
  { name: "ZoomIn Up", value: "animate__zoomInUp" }
]
export const exitTransitions = [
  { name: "BackOut Down", value: "animate__backOutDown" },
  { name: "BackOut Left", value: "animate__backOutLeft" },
  { name: "BackOut Right", value: "animate__backOutRight" },
  { name: "BackOut Up", value: "animate__backOutUp" },
  { name: "BounceOut", value: "animate__bounceOut" },
  { name: "BounceOut Down", value: "animate__bounceOutDown" },
  { name: "BounceOut Left", value: "animate__bounceOutLeft" },
  { name: "BounceOut Right", value: "animate__bounceOutRight" },
  { name: "BounceOut Up", value: "animate__bounceOutUp" },
  { name: "FadeOut", value: "animate__fadeOut" },
  { name: "FadeOut Down", value: "animate__fadeOutDown" },
  { name: "FadeOut Down Big", value: "animate__fadeOutDownBig" },
  { name: "FadeOut Left", value: "animate__fadeOutLeft" },
  { name: "FadeOut Left Big", value: "animate__fadeOutLeftBig" },
  { name: "FadeOut Right", value: "animate__fadeOutRight" },
  { name: "FadeOut Right Big", value: "animate__fadeOutRightBig" },
  { name: "FadeOut Up", value: "animate__fadeOutUp" },
  { name: "FadeOut Up Big", value: "animate__fadeOutUpBig" },
  { name: "FadeOut TopLeft", value: "animate__fadeOutTopLeft" },
  { name: "FadeOut TopRight", value: "animate__fadeOutTopRight" },
  { name: "FadeOut BottomRight", value: "animate__fadeOutBottomRight" },
  { name: "FadeOut BottemLeft", value: "animate__fadeOutBottomLeft" },
  { name: "FlipOut X", value: "animate__flipOutX" },
  { name: "FlipOut Y", value: "animate__flipOutY" },
  { name: "LightSpeedOut Right", value: "animate__lightSpeedOutRight" },
  { name: "LightSpeedOut Left", value: "animate__lightSpeedOutLeft" },
  { name: "RotateOut", value: "animate__rotateOut" },
  { name: "RotateOut DownLeft", value: "animate__rotateOutDownLeft" },
  { name: "RotateOut DownRight", value: "animate__rotateOutDownRight" },
  { name: "RotateOut UpLeft", value: "animate__rotateOutUpLeft" },
  { name: "RotateOut UpRight", value: "animate__rotateOutUpRight" },
  { name: "Hinge", value: "animate__hinge" },
  { name: "RollOut", value: "animate__rollOut" },
  { name: "ZoomOut", value: "animate__zoomOut" },
  { name: "ZoomOut Down", value: "animate__zoomOutDown" },
  { name: "ZoomOut Left", value: "animate__zoomOutLeft" },
  { name: "ZoomOut Right", value: "animate__zoomOutRight" },
  { name: "ZoomOut Up", value: "animate__zoomOutUp" }
]
